### ISSUE TITLE
PY2 = sys.version_info.major == 2 ?

### ISSUE THREAD

**Issue by pinpuk** [reyammer/shellnoob#3]
Python 2.6.5

root@bt:~/Desktop/shellnoob-master# ls
COPYRIGHT  README.md  samples  shellnoob.py  test.py
root@bt:~/Desktop/shellnoob-master# ./shellnoob.py 
Traceback (most recent call last):
  File "./shellnoob.py", line 39, in <module>
    PY2 = sys.version_info.major == 2
AttributeError: 'tuple' object has no attribute 'major'
root@bt:~/Desktop/shellnoob-master# ./shellnoob.py -h
Traceback (most recent call last):
  File "./shellnoob.py", line 39, in <module>
    PY2 = sys.version_info.major == 2
AttributeError: 'tuple' object has no attribute 'major'

**Comment by pinpuk** [comment]
Can you make it compatible with Python 2.6?

**Comment by pinpuk** [comment]
#PY2 = sys.version_info.major == 2
PY2 = sys.version_info[0] == 2

Fixed this way.

**Comment by reyammer** [comment]
Hi @pinpuk, thanks for reporting the issue & finding a workaround. Quick question: did you find python 2.6 being used in some main/big distribution (like Kali linux). If that's the case, then I guess I should support python 2.6 as well!

**Comment by pinpuk** [comment]
Hey @reyammer, Kali Linux is root@kali:~# python -V
Python 2.7.3 , I think you should fix it but it is not a priority :)

**Comment by reyammer** [comment]
awesome, thanks for checking :) I'll add that to the (infinite) todo list :) Thanks!
